### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by jssol** [jssol/catalog-manager#11]
### We are a group of **3**

Here is the link to the [kanban board](https://github.com/jssol/catalog-manager/projects/1)

- @jssol was assigned to `Team member #1` tasks
- @Abenezer-Tilahun was assigned to `Team member #2` tasks
- @saied2035 was assigned to `Team member #3` tasks

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @jssol, @saied2035 and @Abenezer-Tilahun,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
